package com.student.profile.entity;

/**
 * ORM entity representing the {@code courses} table.
 *
 * <p>ER relationship: one Course → many Enrollments.</p>
 */
public class CourseEntity {

    /** Primary key – auto-generated by the database. */
    private Long courseId;

    /** Short course code (e.g. "CS101"). */
    private String courseCode;

    /** Descriptive course name (e.g. "Introduction to Programming"). */
    private String courseName;

    /** Number of credit hours awarded. */
    private Integer credits;

    /** Instructor's full name. */
    private String instructor;

    // ── Getters ───────────────────────────────────────────────────────────

    public Long getCourseId()       { return courseId; }
    public String getCourseCode()   { return courseCode; }
    public String getCourseName()   { return courseName; }
    public Integer getCredits()     { return credits; }
    public String getInstructor()   { return instructor; }

    // ── Setters ───────────────────────────────────────────────────────────

    public void setCourseId(Long courseId)         { this.courseId = courseId; }
    public void setCourseCode(String courseCode)   { this.courseCode = courseCode; }
    public void setCourseName(String courseName)   { this.courseName = courseName; }
    public void setCredits(Integer credits)        { this.credits = credits; }
    public void setInstructor(String instructor)   { this.instructor = instructor; }

    @Override
    public String toString() {
        return "CourseEntity{courseId=" + courseId
                + ", courseCode='" + courseCode + '\''
                + ", courseName='" + courseName + '\''
                + ", credits="     + credits
                + ", instructor='" + instructor + "'}";
    }
}
