package com.student.profile.entity;

/**
 * ORM entity representing the {@code students} table.
 *
 * <p>MyBatis uses getters and setters (JavaBean convention) to map
 * ResultSet columns to object properties.  Column names are mapped to
 * camelCase field names via {@code map-underscore-to-camel-case=true}
 * in {@code application.properties}.</p>
 *
 * <p>ER relationship: one Student → many Enrollments.</p>
 */
public class StudentEntity {

    /** Primary key – auto-generated by the database. */
    private Long studentId;

    /** Student's first name (DB column: {@code first_name}). */
    private String firstName;

    /** Student's last name (DB column: {@code last_name}). */
    private String lastName;

    /** Student's e-mail address (unique). */
    private String email;

    /** Academic major (e.g. "Computer Science"). */
    private String major;

    // ── Getters ───────────────────────────────────────────────────────────

    public Long getStudentId()  { return studentId; }
    public String getFirstName() { return firstName; }
    public String getLastName()  { return lastName; }
    public String getEmail()     { return email; }
    public String getMajor()     { return major; }

    // ── Setters ───────────────────────────────────────────────────────────

    public void setStudentId(Long studentId)   { this.studentId = studentId; }
    public void setFirstName(String firstName) { this.firstName = firstName; }
    public void setLastName(String lastName)   { this.lastName = lastName; }
    public void setEmail(String email)         { this.email = email; }
    public void setMajor(String major)         { this.major = major; }

    /** Convenience: full name for display. */
    public String getFullName() {
        return firstName + " " + lastName;
    }

    @Override
    public String toString() {
        return "StudentEntity{studentId=" + studentId
                + ", firstName='" + firstName + '\''
                + ", lastName='"  + lastName  + '\''
                + ", email='"     + email     + '\''
                + ", major='"     + major     + "'}";
    }
}
